## Exercises in numpy

In [1]:
import numpy as np

### a. Create a null vector of size 10 but the fifth value which is 1

In [2]:
vector_a = np.zeros(10)
vector_a[4] = 1
vector_a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### b. Create a vector with values ranging from 10 to 49

In [3]:
vector_b = np.arange(start=10, stop=50)
vector_b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### c. Reverse a vector (first element becomes last)

In [4]:
np.flip(vector_b)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### d. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
vector_d = np.arange(0, 9)
matrix_d = vector_d.reshape((3,3))
matrix_d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### e. Find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
array_e = np.array([1, 2, 0, 0, 4, 0])
np.argwhere(array_e != 0)

array([[0],
       [1],
       [4]])

### f. Create a random vector of size 30 and find the mean value

In [7]:
vector_f = np.random.rand(30)
np.mean(vector_f)

0.5840764476017358

### g. Create a 2d array with 1 on the border and 0 inside

In [8]:
array_g = np.zeros((5,5))
array_g[:,0] = 1 # first column
array_g[:,-1] = 1 # last column
array_g[0,:] = 1 # first row
array_g[-1,:] = 1 # last row
array_g

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
a = np.zeros(64)
a[::2] = 1
b = a.copy().reshape((8,8))
print(b)
print(np.transpose(b))
# convert to bool and have AND condition

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
rows = np.arange(8)
cols = np.arange(8)

# Compute the checkerboard pattern using broadcasting
checkerboard = (rows[:, np.newaxis] + cols) % 2

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### i. Create a checkerboard 8x8 matrix using the tile function

In [11]:
array_i = np.zeros(16)
array_i[:8:2] = 1
array_i[9::2] = 1
block = array_i.reshape(2,8)
np.tile(block, (8,8))


array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 1.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 1., 0., 1.],
       [1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 1.]])

### j. Given a 1D array, negate all elements which are between 3 and 8, in place

In [12]:
Z = np.arange(11)
filter = np.logical_and(Z >= 3, Z <= 8)
Z[filter] = np.negative(Z[filter])
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


### k. Create a random vector of size 10 and sort it

In [13]:
Z = np.random.random(10)
Z = np.sort(Z)
print(Z)

[0.05212803 0.41709891 0.4682417  0.55444448 0.56215859 0.6078605
 0.70134581 0.72580277 0.84543958 0.96189245]


### l. Consider two random array A anb B, check if they are equal

In [14]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = ...
print(equal)

Ellipsis


### m. How to convert an integer (32 bits) array into a float (32 bits) in place?

In [15]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z.dtype = np.float32
print(Z.dtype)

int32
float32


### n. How to get the diagonal of a dot product?

In [16]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
print(D)

[ 18  66 132]


## 3. Speed optimization using Numpy

See the previous improved version of matmult from day 2.

In [27]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])